### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by SidneyRey** [opendatalab/OmniDocBench#10]
Thank you for your open-source data!
I encountered an issue while testing my self-developed document parsing. The configuration is as follows:
end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        - BLEU
        - METEOR
    display_formula:
      metric:
        - Edit_dist
        - CDM
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      # data_path: ./demo_data/omnidocbench_demo/OmniDocBench_demo.json
      data_path: ./demo_data/OmniDocBench/OmniDocBench.json
    prediction:
      data_path: ./demo_data/hh_OmniDoc_res
    match_method: quick_match
    # filter: 
    #   language: english

The error message is as follows:
raise FileNotFoundError(
FileNotFoundError: Couldn't find a module script at /data/source/ocr/OmniDocBench/bleu/bleu.py. Module 'bleu' doesn't exist on the Hugging Face Hub either.

Could you please advise on how to resolve this?site-packages/evaluate/loading.py", line 681, in evaluation_module_factory

**Comment by ouyanglinke** [comment]
Hi, this issue might be caused by a network proxy. Make sure you can connect to HuggingFace. Here is an issue that might be similar to yours: https://github.com/huggingface/evaluate/issues/456

**Comment by SidneyRey** [comment]
thank you!

**Comment by Rezen1997** [comment]
> thank you!
Hello, have you solved it yet? I still haven't solved the problem by implementing the following method. Can you explain how you did it：
git clone  https://github.com/huggingface/evaluate.git
bleu = evaluate.load("evaluate/metrics/bleu/bleu.py", keep_in_memory=True, experiment_id=random.randint(1,1e8))

It will still report an error:
Traceback (most recent call last):
  File "E:\OminiBeceh\OmniDocBench-main\pdf_validation.py", line 54, in <module>
    val_task(val_dataset, metrics_list, cfg[task]['dataset']['ground_truth']['data_path'], save_name)  # 按页面区分
  File "E:\OminiBeceh\OmniDocBench-main\task\end2end_run_eval.py", line 32, in __init__
    samples, result_s = metric_val(samples).evaluate(group_info, f"{save_name}_{element}")
  File "E:\OminiBeceh\OmniDocBench-main\metrics\cal_metric.py", line 100, in evaluate
    bleu = evaluate.load("evaluate/metrics/bleu/bleu.py", keep_in_memory=True, experiment_id=random.randint(1,1e8))
  File "E:\OminiBeceh\OmniDocBench-main\venv\lib\site-packages\evaluate\loading.py", line 748, in load
    evaluation_module = evaluation_module_factory(
  File "E:\OminiBeceh\OmniDocBench-main\venv\lib\site-packages\evaluate\loading.py", line 616, in evaluation_module_factory
    return LocalEvaluationModuleFactory(
  File "E:\OminiBeceh\OmniDocBench-main\venv\lib\site-packages\evaluate\loading.py", line 421, in get_module
    local_imports = _download_additional_modules(
  File "E:\OminiBeceh\OmniDocBench-main\venv\lib\site-packages\evaluate\loading.py", line 248, in _download_additional_modules
    local_import_path = cached_path(
  File "E:\OminiBeceh\OmniDocBench-main\venv\lib\site-packages\evaluate\utils\file_utils.py", line 175, in cached_path
    output_path = get_from_cache(
  File "E:\OminiBeceh\OmniDocBench-main\venv\lib\site-packages\evaluate\utils\file_utils.py", line 514, in get_from_cache
    raise ConnectionError(f"Couldn't reach {url} ({repr(head_error)})")
ConnectionError: Couldn't reach https://github.com/tensorflow/nmt/raw/master/nmt/scripts/bleu.py (ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'raw.githubusercontent.com\', port=443): Max retries exceeded with url: /tens
orflow/nmt/master/nmt/scripts/bleu.py (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000135F3AE7700>: Failed to resolve \'raw.githubusercontent.com\' ([Errno 11004] getaddrinfo failed)"))')))

**Comment by ouyanglinke** [comment]
It's a network connection issue. Calculating BLEU and METEOR requires a connection to Huggingface. You can try fixing your network proxy. 

Alternatively, you can evaluate only the edit distance without evaluating BLEU and METEOR. You can comment out these two metrics in your config file (e.g., end2end.yaml):

```YAML
...
metric:
        - Edit_dist
        # - BLEU
        # - METEOR
...
```

**Comment by viviansmlie** [comment]
如何在不连接hunggingface的情况下加载本地的包进行bleu的评测呢

**Comment by ouyanglinke** [comment]
> 如何在不连接hunggingface的情况下加载本地的包进行bleu的评测呢

https://github.com/opendatalab/OmniDocBench/issues/26#issuecomment-2688069983
