### ISSUE TITLE
有些版面（比如表格、拼音等）在图中和标注文件中被mask掉了，请问这是出于什么考虑呀

### ISSUE THREAD

**Issue by RDSJC** [opendatalab/OmniDocBench#6]

**Comment by ouyanglinke** [comment]
In the process of constructing the validation set, we applied masking to elements that currently lack standardized formatting (such as pinyin annotated above Chinese text) and those lacking standardized parsing methods (such as tables with images and organic chemical formulas). This was done to prevent accuracy discrepancies due to varying parsing standards across models. These elements are included in the annotation files with bounding boxes but without recognition content. As standards evolve, we may supplement these annotations in the future.
