### ISSUE TITLE
公式识别 和文本识别怎么匹配？

### ISSUE THREAD

**Issue by with-him777** [opendatalab/OmniDocBench#7]
行间公式识别成行内公式、漏检导致数量不一致或者markdown排序不一致 导致公式顺序不一致，会导致 公式无法一对一匹配，这个是怎么做到的呢，目前的公式评估 都是一对一的

**Comment by ouyanglinke** [comment]
We have implemented one-to-one linear sum assignment matching for formulas, rather than direct sequential matching. Therefore, discrepancies in the order and number of formulas will not cause misalignment of all formulas. You will be able to see a detailed description of the matching process in the paper, which will be published in few days.

**Comment by with-him777** [comment]
bleu和meteor值也非常低 是正常的吗 我测试md2md 单个文件 基本上bleu=0 ，然后测试整个目录的mds bleu也比较低

**Comment by ouyanglinke** [comment]
You can see the matching results and the scores corresponding to each sample in the `result/*_quick_match_display_formula_result.json`. If the scores are very low, there is a high possibility that the extraction of interline formulas has failed. You can check whether the model's prediction results represent the interline formulas in LaTeX format (with the correct start and end identifiers).
